<?php

/**
 * BaseOblation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property string $user_name
 * @property integer $category_id
 * @property string $name
 * @property integer $price
 * @property integer $times
 * @property string $images
 * @property string $position
 * @property boolean $can_modify
 * @property boolean $is_rejected
 * @property boolean $is_approved
 * @property string $last_modify
 * @property sfGuardUser $sfGuardUser
 * @property OblationCategory $OblationCategory
 * 
 * @method integer          getUserId()           Returns the current record's "user_id" value
 * @method string           getUserName()         Returns the current record's "user_name" value
 * @method integer          getCategoryId()       Returns the current record's "category_id" value
 * @method string           getName()             Returns the current record's "name" value
 * @method integer          getPrice()            Returns the current record's "price" value
 * @method integer          getTimes()            Returns the current record's "times" value
 * @method string           getImages()           Returns the current record's "images" value
 * @method string           getPosition()         Returns the current record's "position" value
 * @method boolean          getCanModify()        Returns the current record's "can_modify" value
 * @method boolean          getIsRejected()       Returns the current record's "is_rejected" value
 * @method boolean          getIsApproved()       Returns the current record's "is_approved" value
 * @method string           getLastModify()       Returns the current record's "last_modify" value
 * @method sfGuardUser      getSfGuardUser()      Returns the current record's "sfGuardUser" value
 * @method OblationCategory getOblationCategory() Returns the current record's "OblationCategory" value
 * @method Oblation         setUserId()           Sets the current record's "user_id" value
 * @method Oblation         setUserName()         Sets the current record's "user_name" value
 * @method Oblation         setCategoryId()       Sets the current record's "category_id" value
 * @method Oblation         setName()             Sets the current record's "name" value
 * @method Oblation         setPrice()            Sets the current record's "price" value
 * @method Oblation         setTimes()            Sets the current record's "times" value
 * @method Oblation         setImages()           Sets the current record's "images" value
 * @method Oblation         setPosition()         Sets the current record's "position" value
 * @method Oblation         setCanModify()        Sets the current record's "can_modify" value
 * @method Oblation         setIsRejected()       Sets the current record's "is_rejected" value
 * @method Oblation         setIsApproved()       Sets the current record's "is_approved" value
 * @method Oblation         setLastModify()       Sets the current record's "last_modify" value
 * @method Oblation         setSfGuardUser()      Sets the current record's "sfGuardUser" value
 * @method Oblation         setOblationCategory() Sets the current record's "OblationCategory" value
 * 
 * @package    symfonymodel
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOblation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('oblation');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('user_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('price', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('times', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('images', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('position', 'string', 266, array(
             'type' => 'string',
             'default' => 0,
             'length' => 266,
             ));
        $this->hasColumn('can_modify', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('is_rejected', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('is_approved', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('last_modify', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('OblationCategory', array(
             'local' => 'category_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}