<?php

/**
 * BaseComment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property string $user_name
 * @property integer $article_id
 * @property string $content
 * @property string $images
 * @property sfGuardUser $sfGuardUser
 * @property Article $Article
 * 
 * @method integer     getUserId()      Returns the current record's "user_id" value
 * @method string      getUserName()    Returns the current record's "user_name" value
 * @method integer     getArticleId()   Returns the current record's "article_id" value
 * @method string      getContent()     Returns the current record's "content" value
 * @method string      getImages()      Returns the current record's "images" value
 * @method sfGuardUser getSfGuardUser() Returns the current record's "sfGuardUser" value
 * @method Article     getArticle()     Returns the current record's "Article" value
 * @method Comment     setUserId()      Sets the current record's "user_id" value
 * @method Comment     setUserName()    Sets the current record's "user_name" value
 * @method Comment     setArticleId()   Sets the current record's "article_id" value
 * @method Comment     setContent()     Sets the current record's "content" value
 * @method Comment     setImages()      Sets the current record's "images" value
 * @method Comment     setSfGuardUser() Sets the current record's "sfGuardUser" value
 * @method Comment     setArticle()     Sets the current record's "Article" value
 * 
 * @package    symfonymodel
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseComment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('comment');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('user_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('article_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('content', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('images', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Article', array(
             'local' => 'article_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}