<?php

/**
 * BaseRecommend
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $r_type
 * @property string $title
 * @property string $start_date
 * @property string $end_date
 * @property string $image
 * @property string $url
 * 
 * @method string    getRType()      Returns the current record's "r_type" value
 * @method string    getTitle()      Returns the current record's "title" value
 * @method string    getStartDate()  Returns the current record's "start_date" value
 * @method string    getEndDate()    Returns the current record's "end_date" value
 * @method string    getImage()      Returns the current record's "image" value
 * @method string    getUrl()        Returns the current record's "url" value
 * @method Recommend setRType()      Sets the current record's "r_type" value
 * @method Recommend setTitle()      Sets the current record's "title" value
 * @method Recommend setStartDate()  Sets the current record's "start_date" value
 * @method Recommend setEndDate()    Sets the current record's "end_date" value
 * @method Recommend setImage()      Sets the current record's "image" value
 * @method Recommend setUrl()        Sets the current record's "url" value
 * 
 * @package    symfonymodel
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRecommend extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('recommend');
        $this->hasColumn('r_type', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('start_date', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('end_date', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}