<?php

/**
 * BaseFileUpload
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $user_id
 * @property string $file
 * @property sfGuardUser $sfGuardUser
 * 
 * @method string      getUserId()      Returns the current record's "user_id" value
 * @method string      getFile()        Returns the current record's "file" value
 * @method sfGuardUser getSfGuardUser() Returns the current record's "sfGuardUser" value
 * @method FileUpload  setUserId()      Sets the current record's "user_id" value
 * @method FileUpload  setFile()        Sets the current record's "file" value
 * @method FileUpload  setSfGuardUser() Sets the current record's "sfGuardUser" value
 * 
 * @package    symfonymodel
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFileUpload extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('file_upload');
        $this->hasColumn('user_id', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('file', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}