<?php

/**
 * BaseOblationCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $Oblation
 * 
 * @method string              getName()     Returns the current record's "name" value
 * @method Doctrine_Collection getOblation() Returns the current record's "Oblation" collection
 * @method OblationCategory    setName()     Sets the current record's "name" value
 * @method OblationCategory    setOblation() Sets the current record's "Oblation" collection
 * 
 * @package    symfonymodel
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOblationCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('oblation_category');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Oblation', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}