<?php

/**
 * BaseRecommend
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $r_type
 * @property integer $r_id
 * @property string $start_date
 * @property string $end_date
 * @property Article $Article
 * 
 * @method string    getRType()      Returns the current record's "r_type" value
 * @method integer   getRId()        Returns the current record's "r_id" value
 * @method string    getStartDate()  Returns the current record's "start_date" value
 * @method string    getEndDate()    Returns the current record's "end_date" value
 * @method Article   getArticle()    Returns the current record's "Article" value
 * @method Recommend setRType()      Sets the current record's "r_type" value
 * @method Recommend setRId()        Sets the current record's "r_id" value
 * @method Recommend setStartDate()  Sets the current record's "start_date" value
 * @method Recommend setEndDate()    Sets the current record's "end_date" value
 * @method Recommend setArticle()    Sets the current record's "Article" value
 * 
 * @package    symfonymodel
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRecommend extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('recommend');
        $this->hasColumn('r_type', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('r_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('start_date', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('end_date', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Article', array(
             'local' => 'r_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}