<?php

/**
 * BaseAdv
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $block
 * @property string $title
 * @property string $start_date
 * @property string $end_date
 * @property string $url
 * @property string $images
 * 
 * @method string getBlock()      Returns the current record's "block" value
 * @method string getTitle()      Returns the current record's "title" value
 * @method string getStartDate()  Returns the current record's "start_date" value
 * @method string getEndDate()    Returns the current record's "end_date" value
 * @method string getUrl()        Returns the current record's "url" value
 * @method string getImages()     Returns the current record's "images" value
 * @method Adv    setBlock()      Sets the current record's "block" value
 * @method Adv    setTitle()      Sets the current record's "title" value
 * @method Adv    setStartDate()  Sets the current record's "start_date" value
 * @method Adv    setEndDate()    Sets the current record's "end_date" value
 * @method Adv    setUrl()        Sets the current record's "url" value
 * @method Adv    setImages()     Sets the current record's "images" value
 * 
 * @package    symfonymodel
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAdv extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('adv');
        $this->hasColumn('block', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('start_date', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('end_date', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('images', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}