<?php

/**
 * BasePrayWords
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $words
 * 
 * @method string    getWords() Returns the current record's "words" value
 * @method PrayWords setWords() Sets the current record's "words" value
 * 
 * @package    symfonymodel
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePrayWords extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pray_words');
        $this->hasColumn('words', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}