<?php

/**
 * BaseDealList
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property string $description
 * @property boolean $is_in
 * @property integer $ammount
 * @property integer $balance
 * @property sfGuardUser $sfGuardUser
 * 
 * @method integer     getUserId()      Returns the current record's "user_id" value
 * @method string      getDescription() Returns the current record's "description" value
 * @method boolean     getIsIn()        Returns the current record's "is_in" value
 * @method integer     getAmmount()     Returns the current record's "ammount" value
 * @method integer     getBalance()     Returns the current record's "balance" value
 * @method sfGuardUser getSfGuardUser() Returns the current record's "sfGuardUser" value
 * @method DealList    setUserId()      Sets the current record's "user_id" value
 * @method DealList    setDescription() Sets the current record's "description" value
 * @method DealList    setIsIn()        Sets the current record's "is_in" value
 * @method DealList    setAmmount()     Sets the current record's "ammount" value
 * @method DealList    setBalance()     Sets the current record's "balance" value
 * @method DealList    setSfGuardUser() Sets the current record's "sfGuardUser" value
 * 
 * @package    symfonymodel
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDealList extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('deal_list');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('is_in', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('ammount', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('balance', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}