<?php

/**
 * BaseArticle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property string $user_name
 * @property integer $category_id
 * @property string $title
 * @property string $img_one
 * @property string $title_one
 * @property string $img_two
 * @property string $title_two
 * @property string $img_three
 * @property string $title_three
 * @property text $content
 * @property boolean $is_rejected
 * @property boolean $is_approved
 * @property string $last_modify
 * @property sfGuardUser $sfGuardUser
 * @property ArticleCategory $ArticleCategory
 * @property Doctrine_Collection $Comment
 * @property Doctrine_Collection $Recommend
 * 
 * @method integer             getUserId()          Returns the current record's "user_id" value
 * @method string              getUserName()        Returns the current record's "user_name" value
 * @method integer             getCategoryId()      Returns the current record's "category_id" value
 * @method string              getTitle()           Returns the current record's "title" value
 * @method string              getImgOne()          Returns the current record's "img_one" value
 * @method string              getTitleOne()        Returns the current record's "title_one" value
 * @method string              getImgTwo()          Returns the current record's "img_two" value
 * @method string              getTitleTwo()        Returns the current record's "title_two" value
 * @method string              getImgThree()        Returns the current record's "img_three" value
 * @method string              getTitleThree()      Returns the current record's "title_three" value
 * @method text                getContent()         Returns the current record's "content" value
 * @method boolean             getIsRejected()      Returns the current record's "is_rejected" value
 * @method boolean             getIsApproved()      Returns the current record's "is_approved" value
 * @method string              getLastModify()      Returns the current record's "last_modify" value
 * @method sfGuardUser         getSfGuardUser()     Returns the current record's "sfGuardUser" value
 * @method ArticleCategory     getArticleCategory() Returns the current record's "ArticleCategory" value
 * @method Doctrine_Collection getComment()         Returns the current record's "Comment" collection
 * @method Doctrine_Collection getRecommend()       Returns the current record's "Recommend" collection
 * @method Article             setUserId()          Sets the current record's "user_id" value
 * @method Article             setUserName()        Sets the current record's "user_name" value
 * @method Article             setCategoryId()      Sets the current record's "category_id" value
 * @method Article             setTitle()           Sets the current record's "title" value
 * @method Article             setImgOne()          Sets the current record's "img_one" value
 * @method Article             setTitleOne()        Sets the current record's "title_one" value
 * @method Article             setImgTwo()          Sets the current record's "img_two" value
 * @method Article             setTitleTwo()        Sets the current record's "title_two" value
 * @method Article             setImgThree()        Sets the current record's "img_three" value
 * @method Article             setTitleThree()      Sets the current record's "title_three" value
 * @method Article             setContent()         Sets the current record's "content" value
 * @method Article             setIsRejected()      Sets the current record's "is_rejected" value
 * @method Article             setIsApproved()      Sets the current record's "is_approved" value
 * @method Article             setLastModify()      Sets the current record's "last_modify" value
 * @method Article             setSfGuardUser()     Sets the current record's "sfGuardUser" value
 * @method Article             setArticleCategory() Sets the current record's "ArticleCategory" value
 * @method Article             setComment()         Sets the current record's "Comment" collection
 * @method Article             setRecommend()       Sets the current record's "Recommend" collection
 * 
 * @package    symfonymodel
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseArticle extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('article');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('user_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('img_one', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('title_one', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('img_two', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('title_two', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('img_three', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('title_three', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('content', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('is_rejected', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('is_approved', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('last_modify', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('ArticleCategory', array(
             'local' => 'category_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Comment', array(
             'local' => 'id',
             'foreign' => 'article_id'));

        $this->hasMany('Recommend', array(
             'local' => 'id',
             'foreign' => 'r_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}