<?php

/**
 * MemorialTemplateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MemorialTemplateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MemorialTemplateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MemorialTemplate');
    }
}