<?php

/**
 * PayyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PayyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PayyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Payy');
    }
}