<?php

/**
 * Recommend
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    symfonymodel
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Recommend extends BaseRecommend
{
	static public function getFileDir() {
		return sfConfig::get('sf_upload_dir') . '/recommend';
	}

	public function getPublicFileLocation() {
		return self::getFileDir() . '/' . $this->getImage();
	}
	
	public function getPicture($full = false)
	{
		$image = $this->getImage();
		$match = preg_match('^(http|https)://^', $image);
		if ($match){
			return $image;
		}else {
			if ($full){
				return '/uploads/recommend/'.$image;
			}
			else {
				return $image;
			}
		}
	}
}