default: 
  http_metas:
    content-type: text/html

  metas:
    title:        菩萨在线
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [base.css, common.css,/css/jqueryui/themes/base/jquery-ui.css, pages.css, slide.css]

  javascripts:    [jquery-1.9.1.min.js, jquery.slides.min.js]

  has_layout:     true
  layout:         layout
