<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version14 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('temple', 'view', 'integer', '8', array(
             ));
        $this->addColumn('temple', 'xh', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('temple', 'view');
        $this->removeColumn('temple', 'xh');
    }
}