<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version6 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('memorial_template', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'price' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'default' => '0',
              'length' => '8',
             ),
             'is_free' => 
             array(
              'type' => 'boolean',
              'default' => '1',
              'length' => '25',
             ),
             'jng_path' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'lw_path' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'gm_path' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'type' => 'MyISAM',
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->addColumn('memorial', 'template_id', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->dropTable('memorial_template');
        $this->removeColumn('memorial', 'template_id');
    }
}