<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version12 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('memorial_message', 'memorial_message_memorial_id_memorial_id', array(
             'name' => 'memorial_message_memorial_id_memorial_id',
             'local' => 'memorial_id',
             'foreign' => 'id',
             'foreignTable' => 'memorial',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('memorial_message', 'memorial_message_memorial_id', array(
             'fields' => 
             array(
              0 => 'memorial_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('memorial_message', 'memorial_message_memorial_id_memorial_id');
        $this->removeIndex('memorial_message', 'memorial_message_memorial_id', array(
             'fields' => 
             array(
              0 => 'memorial_id',
             ),
             ));
    }
}