<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version7 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('memorial', 'memorial_template_id_memorial_template_id', array(
             'name' => 'memorial_template_id_memorial_template_id',
             'local' => 'template_id',
             'foreign' => 'id',
             'foreignTable' => 'memorial_template',
             'onUpdate' => '',
             'onDelete' => 'SET NULL',
             ));
        $this->addIndex('memorial', 'memorial_template_id', array(
             'fields' => 
             array(
              0 => 'template_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('memorial', 'memorial_template_id_memorial_template_id');
        $this->removeIndex('memorial', 'memorial_template_id', array(
             'fields' => 
             array(
              0 => 'template_id',
             ),
             ));
    }
}