<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version3 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('recommend', 'recommend_r_id_article_id');
    }

    public function down()
    {
        $this->createForeignKey('recommend', 'recommend_r_id_article_id', array(
             'name' => 'recommend_r_id_article_id',
             'local' => 'r_id',
             'foreign' => 'id',
             'foreignTable' => 'article',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
    }
}