<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('recommend', 'r_id');
        $this->addColumn('recommend', 'title', 'string', '255', array(
             ));
        $this->addColumn('recommend', 'image', 'string', '255', array(
             ));
        $this->addColumn('recommend', 'url', 'string', '255', array(
             ));
    }

    public function down()
    {
        $this->addColumn('recommend', 'r_id', 'integer', '8', array(
             ));
        $this->removeColumn('recommend', 'title');
        $this->removeColumn('recommend', 'image');
        $this->removeColumn('recommend', 'url');
    }
}